[actu_6]
alias = "Actu"

title.alias="Titre"
title.select=false
title.type="VarChar"
title.display=true

date.alias="Date"
date.select=false
date.type="Date"
date.display=true

content.alias="Contenu"
content.select=false
content.type="Text"
content.display=false

[edito_6]

alias = "Edito"

title.alias="Titre"
title.select=false
title.type="VarChar"
title.display=true

content.alias="Edito"
content.select=false
content.type="Text"
content.display=false

[album_6]
alias = "Album"

album_name.alias="Titre"
album_name.select=false
album_name.type="VarChar"
album_name.display=true

image.alias="Image"
image.select=false
image.type="VarChar"
image.display=false

artist.alias="Artiste"
artist.select=false
artist.type="VarChar"
artist.display=true

url.alias="Url"
url.select=true
url.type="VarChar"
url.display=false
url.generator_name="genUrl"
url.generator_parameters=["artist","album_name"]

content.alias="Chronique"
content.select=false
content.type="Text"
content.display=false

[concert_6]
alias = "Concert"

url.alias="Url"
url.select=true
url.type="VarChar"
url.display=false
url.generator_name="genUrl"
url.generator_parameters=["artist","place"]

image.alias="Image"
image.select=false
image.type="VarChar"
image.display=false

date.alias="Date"
date.select=false
date.type="Date"
date.display=true

place.alias="Lieu"
place.select=false
place.type="VarChar"
place.display=true

artist.alias="Artiste"
artist.select=false
artist.type="VarChar"
artist.display=true

content.alias="Chronique"
content.select=false
content.type="Text"
content.display=false

[interview_6]
alias = "Interview"

date.alias="Date"
date.select=false
date.type="Date"
date.display=true

image.alias="Image"
image.select=false
image.type="VarChar"
image.display=false

artist.alias="Artiste"
artist.select=false
artist.type="VarChar"
artist.display=true

url.alias="Url"
url.select=true
url.type="VarChar"
url.display=false
url.generator_name="genUrl"
url.generator_parameters=["artist","album_name"]

content.alias="Contenu"
content.select=false
content.type="Text"
content.display=false
