[actu_6]
alias = "Actu"

[[actu_6.fields]]
name = "title"
alias = "Titre"
select=false
type="VarChar"
display=true

[[actu_6.fields]]
name = "date"
alias="Date"
select=false
type="Date"
display=true

[[actu_6.fields]]
name = "content"
alias="Contenu"
select=false
type="Text"
display=false

[edito_6]

alias = "Edito"

[[edito_6.fields]]
name="title"
alias="Titre"
select=false
type="VarChar"
display=true

[[edito_6.fields]]
name="content"
alias="Edito"
select=false
type="Text"
display=false

[album_6]
alias = "Album"

[[album_6.fields]]
name="album_name"
alias="Titre"
select=false
type="VarChar"
display=true

[[album_6.fields]]
name="image"
alias="Image"
select=false
type="VarChar"
display=false

[[album_6.fields]]
name="artist"
alias="Artiste"
select=false
type="VarChar"
display=true

[[album_6.fields]]
name="url"
alias="Url"
select=true
type="VarChar"
display=false
generator_name="genUrl"
generator_parameters=["artist","album_name"]

[[album_6.fields]]
name="content"
alias="Chronique"
select=false
type="Text"
display=false

[concert_6]
alias = "Concert"

[[concert_6.fields]]
name="url"
alias="Url"
select=true
type="VarChar"
display=false
generator_name="genUrl"
generator_parameters=["artist","place"]

[[concert_6.fields]]
name="image"
alias="Image"
select=false
type="VarChar"
display=false

[[concert_6.fields]]
name="date"
alias="Date"
select=false
type="Date"
display=true

[[concert_6.fields]]
name="place"
alias="Lieu"
select=false
type="VarChar"
display=true

[[concert_6.fields]]
name="artist"
alias="Artiste"
select=false
type="VarChar"
display=true

[[concert_6.fields]]
name="content"
alias="Chronique"
select=false
type="Text"
display=false

[interview_6]
alias = "Interview"

[[interview_6.fields]]
name="date"
alias="Date"
select=false
type="Date"
display=true

[[interview_6.fields]]
name="image"
alias="Image"
select=false
type="VarChar"
display=false

[[interview_6.fields]]
name="artist"
alias="Artiste"
select=false
type="VarChar"
display=true

[[interview_6.fields]]
name="url"
alias="Url"
select=true
type="VarChar"
display=false
generator_name="genUrl"
generator_parameters=["artist","album_name"]

[[interview_6.fields]]
name="content"
alias="Contenu"
select=false
type="Text"
display=false
