[actu_6]
alias = "Actu"

[actu_6.title]
alias = "Titre"
select=false
type="VarChar"
display=true

[actu_6.date]
alias="Date"
select=false
type="Date"
display=true

[actu_6.content]
alias="Contenu"
select=false
type="Text"
display=false

[edito_6]

alias = "Edito"

[edito_6.title]
alias="Titre"
select=false
type="VarChar"
display=true

[edito_6.content]
alias="Edito"
select=false
type="Text"
display=false

[album_6]
alias = "Album"

[album_6.album_name]
alias="Titre"
select=false
type="VarChar"
display=true

[album_6.image]
alias="Image"
select=false
type="VarChar"
display=false

[album_6.artist]
alias="Artiste"
select=false
type="VarChar"
display=true

[album_6.url]
alias="Url"
select=true
type="VarChar"
display=false
generator_name="genUrl"
generator_parameters=["artist","album_name"]

[album_6.content]
alias="Chronique"
select=false
type="Text"
display=false

[concert_6]
alias = "Concert"

[concert_6.url]
alias="Url"
select=true
type="VarChar"
display=false
generator_name="genUrl"
generator_parameters=["artist","place"]

[concert_6.image]
alias="Image"
select=false
type="VarChar"
display=false

[concert_6.date]
alias="Date"
select=false
type="Date"
display=true

[concert_6.place]
alias="Lieu"
select=false
type="VarChar"
display=true

[concert_6.artist]
alias="Artiste"
select=false
type="VarChar"
display=true

[concert_6.content]
alias="Chronique"
select=false
type="Text"
display=false

[interview_6]
alias = "Interview"

[interview_6.date]
alias="Date"
select=false
type="Date"
display=true

[interview_6.image]
alias="Image"
select=false
type="VarChar"
display=false

[interview_6.artist]
alias="Artiste"
select=false
type="VarChar"
display=true

[interview_6.url]
alias="Url"
select=true
type="VarChar"
display=false
generator_name="genUrl"
generator_parameters=["artist","album_name"]

[interview_6.content]
alias="Contenu"
select=false
type="Text"
display=false
